services:

  mongo:
    container_name: panoptes-mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    expose:
      - "27017"
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
      - ./seed/mongo:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD-SHELL", "mongosh --quiet --eval 'db.adminCommand({ ping: 1 })' > /dev/null" ]
      interval: 5s
      timeout: 5s
      retries: 30
    networks:
      - pol-tijdschriften

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: panoptes-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - '9200:9200'
      - '9300:9300'
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:9200 >/dev/null" ]
      interval: 5s
      timeout: 5s
      retries: 60
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - pol-tijdschriften

  # Use this if you want to seed the Elasticsearch database with data
  #
  # es-init:
  #   image: curlimages/curl:latest
  #   container_name: panoptes-es-init
  #   depends_on:
  #     elastic: { condition: service_healthy }
  #   volumes:
  #     - ./seed/es:/seed:ro
  #     - ./seed/es/es-init.sh:/usr/local/bin/es-init.sh:ro
  #   entrypoint: ["/bin/sh","/usr/local/bin/es-init.sh"]
  #   restart: "no"
  #   networks:
  #     - pol-tijdschriften

  panoptes:
    container_name: panoptes-api
    image: registry.diginfra.net/tsd/panoptes-backend:beta-60
    platform: linux/amd64
    environment:
      - ES_SCHEME=http
      - ES_HOST=elastic
      - ES_PORT=9200
      - MONGO_CONNECTION=mongodb://mongo:27017/
    depends_on:
      mongo:
        condition: service_healthy
      elastic:
        condition: service_healthy
      #es-init:
      #  condition: service_completed_successfully
    ports:
      - "8000:8000"
    networks:
      - pol-tijdschriften

volumes:
  es-data:
  mongo-data:

networks:
  pol-tijdschriften: