[index]
full_text="yes"
name="tijdschriften-plaatsnaam"
record="yes"

[index.input]
format="json"

[index.id]
path="jmes:rowId"
type="keyword"

[index.facet.placeId]
path="jmes:Plaats_ID"
type="text"

[index.facet.placeName]
path="jmes:name"
type="text"

[index.facet.country]
path="jmes:country"
type="text"

[index.facet.countryGeoCode]
path="jmes:country_GeoNames"
type="text"

[index.facet.latitude]
path="jmes:Latitude"
type="number"

[index.facet.longitude]
path="jmes:Longitude"
type="number"

[index.facet.geoNameURI]
path="jmes:GeoNames_uri"
type="text"
