[index]
full_text="yes"
name="tijdschriften-personen"
record="yes"

[index.input]
format="json"

[index.id]
path="jmes:rowId"
type="keyword"

[index.facet.personId]
path="jmes:ID_def"
type="text"

[index.facet.personName]
path="jmes:Name"
type="text"

[index.facet.yearOfBirth]
path="jmes:geboortejaar"
type="text"

[index.facet.yearOfDeath]
path="jmes:sterfjaar"
type="text"

[index.facet.bioPortaal]
path="jmes:Bioportaal"
type="text"

[index.facet.bioNumber]
path="jmes:Bionummer"
type="text"

[index.facet.politicalPosition]
path="jmes:\"Politieke positie\""
type="text"

[index.facet.occupation1]
path="jmes:Beroep_1"
type="text"

[index.facet.occupation1Remark]
path="jmes:Beroep_1_opmerking"
type="text"

[index.facet.occupation2]
path="jmes:Beroep_2"
type="text"

[index.facet.occupation3]
path="jmes:Beroep_3"
type="text"



