[index]
full_text="yes"
name="tijdschriften-uitgever_drukker"
record="yes"

[index.input]
format="json"

[index.id]
path="jmes:rowId"
type="keyword"

[index.facet.publisherId]
path="jmes:Uitgever_ID_nieuw"
type="text"

[index.facet.publisher]
path="jmes:Uitgeverij"
type="text"

[index.facet.firstGenerationId]
path="jmes:Eerste_generatie_ID"
type="keyword"

[index.facet.secondGenerationId]
path="jmes:Tweede_generatie_ID"
type="keyword"

[index.facet.place1Id]
path="jmes:Plaats1_ID"
type="text"

[index.facet.place1Remark]
path="jmes:Plaats1_opmerking"
type="text"

[index.facet.place2Id]
path="jmes:Plaats2_ID"
type="text"

[index.facet.place3Id]
path="jmes:Plaats3_ID"
type="text"

[index.facet.politicalSignature]
path="jmes:\"Politiek signatuur\""
type="text"

[index.facet.existence]
path="jmes:Bestaan"
type="text"
